[package]
name = "lid"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false